// Generated by CoffeeScript 1.7.1
(function() {
  var COLORS, colors, exec, git, html, jobs, mongo, parseSequence, runFile, runNextJob, runTask, runner, server, spawn, tokenize, updateLog;

  colors = require('colors');

  git = require('./git');

  server = require('./server');

  exec = require('child_process').exec;

  spawn = require('child_process').spawn;

  mongo = require('mongodb');

  jobs = require('./jobs');

  parseSequence = function(input) {
    var length;
    length = input.length;
    return {
      cmd: input[length - 1],
      args: input.substring(2, length - 1)
    };
  };

  tokenize = function(input, result) {
    if (result == null) {
      result = [];
    }
    if (input === '') {
      return [''];
    }
    input.replace(/(\u001B\[.*?([@-~]))|([^\u001B]+)/g, function(m) {
      return result.push(m[0] === '\u001B' && parseSequence(m) || m);
    });
    return result;
  };

  COLORS = {
    0: '',
    1: 'bold',
    4: 'underscore',
    5: 'blink',
    30: 'fg-black',
    31: 'fg-red',
    32: 'fg-green',
    33: 'fg-yellow',
    34: 'fg-blue',
    35: 'fg-magenta',
    36: 'fg-cyan',
    37: 'fg-white',
    40: 'bg-black',
    41: 'bg-red',
    42: 'bg-green',
    43: 'bg-yellow',
    44: 'bg-blue',
    45: 'bg-magenta',
    46: 'bg-cyan',
    47: 'bg-white'
  };

  html = function(input) {
    var result;
    result = input.map(function(v) {
      var cls;
      if (typeof v === 'string') {
        return v;
      } else if (v.cmd === 'm') {
        cls = v.args.split(';').map(function(v) {
          return COLORS[parseInt(v)];
        }).join(' ');
        return '';
      } else {
        return '';
      }
    });
    return result.join(' ');
  };

  runner = module.exports = {
    build: function() {
      return runNextJob();
    }
  };

  runNextJob = function() {
    if (jobs.current != null) {
      return false;
    }
    return jobs.next(function() {
      return git.pull(function() {
        return runTask(function(success) {
          return jobs.currentComplete(success, function() {
            return runNextJob();
          });
        });
      });
    });
  };

  runTask = function(next) {
    var interval, j, logQ, processLogQ;
    logQ = [];
    logQ.push(["Executing '" + git.runner + "'\n\n", false]);
    logQ.push(["Running build task: " + git.runner + "\n\n", false]);
    j = spawn("/bin/bash", [git.runner]);
    j.stdout.on('data', (function(_this) {
      return function(data) {
        return logQ.push([data, false]);
      };
    })(this));
    j.stderr.on('data', (function(_this) {
      return function(data) {
        return logQ.push([data, true]);
      };
    })(this));
    j.on('error', (function(_this) {
      return function(err) {
        return logQ.push([
          "Caught error running task " + err.message + "\n\n", true, function() {
            return runFile(git.failure, next, true);
          }
        ]);
      };
    })(this));
    j.on('close', (function(_this) {
      return function(code) {
        if (code === 0) {
          return logQ.push([
            "Process exitied with code " + code + "\n\n", false, function() {
              return runFile(git.success, next, true);
            }
          ]);
        } else {
          return logQ.push([
            "Process exited with code " + code + "\n\n", true, function() {
              return runFile(git.failure, next, false);
            }
          ]);
        }
      };
    })(this));
    interval = null;
    processLogQ = function() {
      var args;
      if (interval) {
        clearInterval(interval);
      }
      if (logQ.length === 0) {
        interval = setInterval(processLogQ, 1000);
        return;
      }
      args = logQ.shift();
      if (args.length === 3) {
        return updateLog.apply(this, args);
      } else {
        return updateLog.apply(this, args.concat(function() {
          return processLogQ();
        }));
      }
    };
    return interval = setInterval(processLogQ, 1000);
  };

  runFile = function(file, next, args) {
    if (args == null) {
      args = null;
    }
    return jobs.updateLog(jobs.current, "Executing " + file, function() {
      console.log(("Executing " + file).grey);
      return exec(file, (function(_this) {
        return function(error, stdout, stderr) {
          if (error != null) {
            return updateLog(error, true, function() {
              return updateLog(stdout, true, function() {
                return updateLog(stderr, true, function() {
                  return next(args);
                });
              });
            });
          } else {
            return updateLog(stdout, true, function() {
              return next(args);
            });
          }
        };
      })(this));
    });
  };

  updateLog = function(buffer, isError, done) {
    var content, errorClass;
    content = html(tokenize(buffer.toString()));
    if (isError) {
      errorClass = ' error';
      console.log(("" + content).red);
    } else {
      errorClass = '';
      console.log(content);
    }
    return jobs.updateLog(jobs.current, content, done);
  };

}).call(this);
